/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProtectedSidebarRouteRouteImport } from './routes/_protected/_sidebar/route'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ProtectedWorkspaceCreateRouteImport } from './routes/_protected/workspace/create'
import { Route as ProtectedAcceptInvitationInvitationIdRouteImport } from './routes/_protected/accept-invitation/$invitationId'
import { Route as ProtectedSidebarProfileRouteImport } from './routes/_protected/_sidebar/profile'
import { Route as ProtectedSidebarDashboardRouteImport } from './routes/_protected/_sidebar/dashboard'
import { Route as ProtectedSidebarWorkspaceSettingsRouteImport } from './routes/_protected/_sidebar/workspace/settings'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedSidebarRouteRoute = ProtectedSidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkspaceCreateRoute =
  ProtectedWorkspaceCreateRouteImport.update({
    id: '/workspace/create',
    path: '/workspace/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAcceptInvitationInvitationIdRoute =
  ProtectedAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSidebarProfileRoute = ProtectedSidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedSidebarRouteRoute,
} as any)
const ProtectedSidebarDashboardRoute =
  ProtectedSidebarDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedSidebarRouteRoute,
  } as any)
const ProtectedSidebarWorkspaceSettingsRoute =
  ProtectedSidebarWorkspaceSettingsRouteImport.update({
    id: '/workspace/settings',
    path: '/workspace/settings',
    getParentRoute: () => ProtectedSidebarRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof ProtectedSidebarDashboardRoute
  '/profile': typeof ProtectedSidebarProfileRoute
  '/accept-invitation/$invitationId': typeof ProtectedAcceptInvitationInvitationIdRoute
  '/workspace/create': typeof ProtectedWorkspaceCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/workspace/settings': typeof ProtectedSidebarWorkspaceSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard': typeof ProtectedSidebarDashboardRoute
  '/profile': typeof ProtectedSidebarProfileRoute
  '/accept-invitation/$invitationId': typeof ProtectedAcceptInvitationInvitationIdRoute
  '/workspace/create': typeof ProtectedWorkspaceCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/workspace/settings': typeof ProtectedSidebarWorkspaceSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected/_sidebar': typeof ProtectedSidebarRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_protected/_sidebar/dashboard': typeof ProtectedSidebarDashboardRoute
  '/_protected/_sidebar/profile': typeof ProtectedSidebarProfileRoute
  '/_protected/accept-invitation/$invitationId': typeof ProtectedAcceptInvitationInvitationIdRoute
  '/_protected/workspace/create': typeof ProtectedWorkspaceCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_protected/_sidebar/workspace/settings': typeof ProtectedSidebarWorkspaceSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/profile'
    | '/accept-invitation/$invitationId'
    | '/workspace/create'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/workspace/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
    | '/profile'
    | '/accept-invitation/$invitationId'
    | '/workspace/create'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/workspace/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/_protected/_sidebar'
    | '/auth/login'
    | '/auth/register'
    | '/_protected/_sidebar/dashboard'
    | '/_protected/_sidebar/profile'
    | '/_protected/accept-invitation/$invitationId'
    | '/_protected/workspace/create'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_protected/_sidebar/workspace/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/_sidebar': {
      id: '/_protected/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedSidebarRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/workspace/create': {
      id: '/_protected/workspace/create'
      path: '/workspace/create'
      fullPath: '/workspace/create'
      preLoaderRoute: typeof ProtectedWorkspaceCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/accept-invitation/$invitationId': {
      id: '/_protected/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof ProtectedAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/_sidebar/profile': {
      id: '/_protected/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedSidebarProfileRouteImport
      parentRoute: typeof ProtectedSidebarRouteRoute
    }
    '/_protected/_sidebar/dashboard': {
      id: '/_protected/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedSidebarDashboardRouteImport
      parentRoute: typeof ProtectedSidebarRouteRoute
    }
    '/_protected/_sidebar/workspace/settings': {
      id: '/_protected/_sidebar/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof ProtectedSidebarWorkspaceSettingsRouteImport
      parentRoute: typeof ProtectedSidebarRouteRoute
    }
  }
}

interface ProtectedSidebarRouteRouteChildren {
  ProtectedSidebarDashboardRoute: typeof ProtectedSidebarDashboardRoute
  ProtectedSidebarProfileRoute: typeof ProtectedSidebarProfileRoute
  ProtectedSidebarWorkspaceSettingsRoute: typeof ProtectedSidebarWorkspaceSettingsRoute
}

const ProtectedSidebarRouteRouteChildren: ProtectedSidebarRouteRouteChildren = {
  ProtectedSidebarDashboardRoute: ProtectedSidebarDashboardRoute,
  ProtectedSidebarProfileRoute: ProtectedSidebarProfileRoute,
  ProtectedSidebarWorkspaceSettingsRoute:
    ProtectedSidebarWorkspaceSettingsRoute,
}

const ProtectedSidebarRouteRouteWithChildren =
  ProtectedSidebarRouteRoute._addFileChildren(
    ProtectedSidebarRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedSidebarRouteRoute: typeof ProtectedSidebarRouteRouteWithChildren
  ProtectedAcceptInvitationInvitationIdRoute: typeof ProtectedAcceptInvitationInvitationIdRoute
  ProtectedWorkspaceCreateRoute: typeof ProtectedWorkspaceCreateRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedSidebarRouteRoute: ProtectedSidebarRouteRouteWithChildren,
  ProtectedAcceptInvitationInvitationIdRoute:
    ProtectedAcceptInvitationInvitationIdRoute,
  ProtectedWorkspaceCreateRoute: ProtectedWorkspaceCreateRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
